version: "3.3"
services:
  catalogue:
    image: 'cataloguedev:${TAG-latest}'
    container_name: app-solo
    volumes:
      - ./catalogue:/app
    env_file:
      - .env
      - .env.solo
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}:${SOLODEVPORT}
      - PORT
      - BASE_PATH=
    build:
      context: .
      dockerfile: Dockerfile.catalogue
      target: dev
    ports:
      - "${SOLODEVPORT}:${PORT}"
    networks:
      - default

  db:
    container_name: db
    image: postgres:12
    build:
      context: .
      dockerfile: Dockerfile.postgres
    #volumes:
    #  - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.solo
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME?Variable not set}.app-db-data == true
    networks:
      - default

networks:
  traefik-public:
  default:
