version: "3.3"
services:
  catalogue:
    image: 'cataloguedev:${TAG-latest}'
    container_name: catalogue-solo
    volumes:
      - ./catalogue:/app
    env_file:
      - .env
      - .env.solo
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=http://${DOMAIN?Variable not set}:${SOLODEVPORT}
      - PORT
      - BASE_PATH=
    build:
      context: .
      dockerfile: Dockerfile.catalogue
      target: dev
    ports:
      - "${SOLODEVPORT}:${PORT}"

  db:
    container_name: db-solo
    image: postgres-solo
    build:
      context: .
      dockerfile: Dockerfile.postgres
    #volumes:
    #  - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.solo
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5