version: "3.3"
services:
  #redis:
  #  container_name: cache
  #  image: "redis:alpine"
  #  networks:
  #    - default  
  #  environment:
  #    - REDIS_PASSWORD=${CACHE_PASSWORD}
  #    - REDIS_REPLICATION_MODE=master
  #  ports:
  #    - "6379:6379"
  #  volumes:
  #    # save redisearch data to your current working directory
  #    - redis-data:/data
  #  command:
  #    # Save if 100 keys are added in every 10 seconds
  #    - "--save 10 100"
  #    # Set password
  #    - "--requirepass ${CACHE_PASSWORD}"  
  #
  #redisinsight: # redis db visualization dashboard
  #  container_name: cache-mon
  #  image: redislabs/redisinsight
  #  ports:
  #    - 8001:8001
  #  volumes:
  #    - redisinsight:/db
  #  networks:
  #    - default
  db:
    container_name: db
    image: postgres:12
    build:
      context: .
      dockerfile: Dockerfile.postgres
    #volumes:
    #  - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME?Variable not set}.app-db-data == true
          
  catalogue:
    image: 'catalogueprod:${TAG-latest}'
    container_name: app-prod
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - PORT=${PORT}
      # Allow explicit env var override for tests
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.catalogue
      target: prod
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not set}-catalogue-http.rule=PathPrefix(`/catalogue`)
        - traefik.http.services.${STACK_NAME?Variable not set}-catalogue.loadbalancer.server.port=${PORT}
        - traefik.http.routers.${STACK_NAME?Variable not set}-catalogue-http.middlewares=catalogue-stripprefix
        - traefik.http.middlewares.catalogue-stripprefix.stripprefix.prefixes=/catalogue
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    external: true

volumes:
  redis-data:
  redisinsight: