version: "3.3"
services:

  catalogue:
    image: 'cataloguedev:${TAG-latest}'
    container_name: catalogue-integrated
    volumes:
      - ./catalogue:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}/catalogue
      - PORT=${PORT}
      - BASE_PATH=/catalogue
    build:
      context: .
      dockerfile: Dockerfile.catalogue
      target: dev
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-catalogue-http.rule=PathPrefix(`/catalogue`)
      - traefik.http.services.${STACK_NAME?Variable not set}-catalogue.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${STACK_NAME?Variable not set}-catalogue-http.middlewares=catalogue-stripprefix
      - traefik.http.middlewares.catalogue-stripprefix.stripprefix.prefixes=/catalogue

