"""greengage_fields

Revision ID: 44ad407bc04e
Revises: 27c8315a7dd8
Create Date: 2024-01-11 16:05:21.793515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44ad407bc04e'
down_revision = '27c8315a7dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interlinker', sa.Column('authors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('interlinker', sa.Column('citizen_science_description_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.add_column('interlinker', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('interlinker', sa.Column('doi', sa.String(), nullable=True))
    op.add_column('interlinker', sa.Column('themes', sa.String(), nullable=True))
    op.add_column('interlinker', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('interlinker', sa.Column('external_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interlinker', 'external_link')
    op.drop_column('interlinker', 'publisher')
    op.drop_column('interlinker', 'themes')
    op.drop_column('interlinker', 'doi')
    op.drop_column('interlinker', 'creation_date')
    op.drop_column('interlinker', 'citizen_science_description_translations')
    op.drop_column('interlinker', 'authors')
    # ### end Alembic commands ###
