"""themes

Revision ID: 57af1c829618
Revises: 6e5462714d5d
Create Date: 2024-01-15 16:35:30.844823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57af1c829618'
down_revision = '6e5462714d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
