"""cs_description

Revision ID: 6e5462714d5d
Revises: 4f393c0c1381
Create Date: 2024-01-15 14:34:39.581653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5462714d5d'
down_revision = '4f393c0c1381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
